{-# LANGUAGE OverloadedStrings #-}
module Templates (layout) where

import Data.Text (Text)
import qualified Data.Text as T

-- | Main layout with sidebar and content area.
layout :: [String] -> String -> Text -> Text
layout chapters currentChapter content = T.unlines
    [ "<!DOCTYPE html>"
    , "<html lang=\"pt-BR\">"
    , "<head>"
    , "    <meta charset=\"UTF-8\">"
    , "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    , "    <title>Haskell Documentation Reader</title>"
    , "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">"
    , "    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>"
    , "    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&family=Outfit:wght@500;700&display=swap\" rel=\"stylesheet\">"
    , "    <style>"
    , "        :root {"
    , "            --bg-color: #050505;"
    , "            --sidebar-bg: rgba(20, 20, 25, 0.7);"
    , "            --accent-color: #6366f1;"
    , "            --text-main: #e2e8f0;"
    , "            --text-dim: #94a3b8;"
    , "            --glass-border: rgba(255, 255, 255, 0.1);"
    , "        }"
    , "        body {"
    , "            background-color: var(--bg-color);"
    , "            color: var(--text-main);"
    , "            font-family: 'Inter', sans-serif;"
    , "            margin: 0;"
    , "            display: flex;"
    , "            height: 100vh;"
    , "            overflow: hidden;"
    , "        }"
    , "        /* Sidebar Styles */"
    , "        aside {"
    , "            width: 300px;"
    , "            background: var(--sidebar-bg);"
    , "            backdrop-filter: blur(12px);"
    , "            border-right: 1px solid var(--glass-border);"
    , "            display: flex;"
    , "            flex-direction: column;"
    , "            padding: 2rem 1rem;"
    , "            overflow-y: auto;"
    , "        }"
    , "        h1 {"
    , "            font-family: 'Outfit', sans-serif;"
    , "            font-size: 1.5rem;"
    , "            margin-bottom: 2rem;"
    , "            padding-left: 0.5rem;"
    , "            background: linear-gradient(90deg, #818cf8, #c084fc);"
    , "            -webkit-background-clip: text;"
    , "            -webkit-text-fill-color: transparent;"
    , "        }"
    , "        nav a {"
    , "            display: block;"
    , "            padding: 0.75rem 1rem;"
    , "            color: var(--text-dim);"
    , "            text-decoration: none;"
    , "            border-radius: 8px;"
    , "            margin-bottom: 0.5rem;"
    , "            transition: all 0.3s ease;"
    , "            font-size: 0.95rem;"
    , "        }"
    , "        nav a:hover {"
    , "            background: rgba(255, 255, 255, 0.05);"
    , "            color: var(--text-main);"
    , "        }"
    , "        nav a.active {"
    , "            background: rgba(99, 102, 241, 0.15);"
    , "            color: var(--accent-color);"
    , "            border-left: 3px solid var(--accent-color);"
    , "        }"
    , "        /* Main Content */"
    , "        main {"
    , "            flex: 1;"
    , "            overflow-y: auto;"
    , "            padding: 4rem 2rem;"
    , "            scroll-behavior: smooth;"
    , "        }"
    , "        .content-wrapper {"
    , "            max-width: 800px;"
    , "            margin: 0 auto;"
    , "            animation: fadeIn 0.5s ease-out;"
    , "        }"
    , "        @keyframes fadeIn {"
    , "            from { opacity: 0; transform: translateY(10px); }"
    , "            to { opacity: 1; transform: translateY(0); }"
    , "        }"
    , "        /* Markdown Typography */"
    , "        h1, h2, h3 { font-family: 'Outfit', sans-serif; }"
    , "        pre {"
    , "            background: #111;"
    , "            padding: 1.5rem;"
    , "            border-radius: 12px;"
    , "            border: 1px solid var(--glass-border);"
    , "            overflow-x: auto;"
    , "        }"
    , "        code { font-family: 'Fira Code', monospace; color: #a5b4fc; }"
    , "        img { max-width: 100%; border-radius: 12px; margin: 2rem 0; }"
    , "        blockquote {"
    , "            border-left: 4px solid var(--accent-color);"
    , "            margin: 0;"
    , "            padding: 0.5rem 1.5rem;"
    , "            background: rgba(255, 255, 255, 0.03);"
    , "            color: var(--text-dim);"
    , "        }"
    , "    </style>"
    , "</head>"
    , "<body>"
    , "    <aside>"
    , "        <h1>Haskell Reader</h1>"
    , "        <nav>"
    ,           T.concat (map (renderLink currentChapter) chapters)
    , "        </nav>"
    , "    </aside>"
    , "    <main>"
    , "        <article class=\"content-wrapper\">"
    ,           content
    , "        </article>"
    , "    </main>"
    , "</body>"
    , "</html>"
    ]

renderLink :: String -> String -> Text
renderLink current name = 
    let activeClass = if name == current then " class=\"active\"" else ""
    in  "<a href=\"/" <> T.pack name <> "\"" <> T.pack activeClass <> ">" <> T.pack name <> "</a>"
